name: create_endpoint

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Environment of the EdgeCoreServices Team, right now is usually QA'
        required: true
        type: choice
        options:
        - dev
        - qa
        - prod
      ORIGIN_ACCOUNT:
        description: 'AWS Account from the Prod Team (12 Numbers)'
        required: true
      CUSTOMER_ENVIRONMENT:
        description: 'The stage/env of the Product Team'
        required: true
        type: choice
        options:
        - dev
        - qa
        - prod
      CLUSTER_ID:
        description: 'The Cluster ID (from Rancher)'
        required: true
      SQS_DESTINATION:
        description: 'URL to call to create the endpoints, usually https://sqs.eu-central-1.amazonaws.com/{ORIGIN_ACCOUNT}/iot-queue-edge'
        required: true
      RANCHER_INSTANCE:
        description: 'Name of the Rancher instance the K8s cluster is running. E.g: dev-green, eu-lni'
        required: true
      VAULT_TOKEN:
        description: 'A Vault Token is required to execute Vault, right now a temporary token has to be created manually and pasted here'
        required: true


jobs:
  RunTheScript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: uses: hashicorp/vault-action@v2.4.2
      - name: Bash execution
        run: 
          bash create_endpoint.sh -h
