name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.17'

      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2

          golangci-lint run --skip-dirs='(internal|test)'


  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Go   
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: carles6/golang-swagger-actions-rc:latest
      - name: Run e2e tests
        uses: addnab/docker-run-action@v3
        id: runner
        with:
          image: carles6/golang-swagger-actions-rc:latest
          run: |
            export SQS_QUEUE_URL=${{ secrets.SQS_QUEUE_URL }}
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}
            export GOCACHE=/tmp/
            cd / && ./go-rest-api & cd /app && go test ./test/e2e --sqsQueueUrl=$SQS_QUEUE_URL --appUrl=http://localhost:8080
      - name: Run commands
        run : |
          echo 'HELLO WORLD!'
          go version
      - name: Push to Registry and build Portability
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: carles6/golang-swagger-actions-rc:latest

  test:
    runs-on: ubuntu-latest
    services:
      swagger-go:
        image: carles6/golang-swagger-actions-rc:latest
        ports:
          - 8080:8080
        env:
          SQS_QUEUE_URL: ${{ secrets.SQS_QUEUE_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}  

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
